### ISSUE TITLE
Load Default Properties if Game.dll is not Found

### ISSUE THREAD

**Issue by Axanery** [RSDKModding/RetroED#122]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this feature has not already been requested.
- [X] I acknowledge the addition of this feature is neither guaranteed nor a priority.
- [x] This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### Requested Feature

As it stands right now, there are no properties being hashed for objects as the editor expects a Game.dll file. If there is no Game.dll file, properties show up as MD5 hashes and cannot be edited. The editor considers them invalid data and removes all properties from every single  entity if the scene is synced to the StageConfig. I think there should be both 1) a list of default properties built into the editor for hashing and 2) a way to load a property list outside of Game.dll so that this "invalid data" is not removed.
[PropertyList.txt](https://github.com/user-attachments/files/16215404/PropertyList.txt)
![image](https://github.com/user-attachments/assets/e09dea7c-cbc0-4893-95e5-3415240fde1b)

**Comment by Leonx254** [comment]
Bug fix and Requested feature added in 043ea23
