### ISSUE TITLE
Color Picker tool for Palette Editor

### ISSUE THREAD

**Issue by KiaraGale** [RSDKModding/RetroED#123]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this feature has not already been requested.
- [X] I acknowledge the addition of this feature is neither guaranteed nor a priority.
- [X] This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.

### Editor Tool

Palette Editor

### Requested Feature

Being able to use a color picker tool in RetroED would be incredible, as the absence of this gives programs like ManiaPal a leg up in this regard.
It would also make it easier to directly grab colors from a sprite sheet in a sprite editing program and put it into a Game/StageConfig file, rather than having to grab the hex code/RGB/HSL values of a color and manually input them.

**Comment by Leonx254** [comment]
Added in e2c9219
