### ISSUE TITLE
[Scene Editor - v5] Tell user if game logic file fails to load and why

### ISSUE THREAD

**Issue by MegAmi24** [RSDKModding/RetroED#125]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this feature has not already been requested.
- [X] I acknowledge the addition of this feature is neither guaranteed nor a priority.
- [X] This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### Requested Feature

When loading a v5 scene, the editor should say somewhere if game logic doesn't load, and if so, why (e.g. file not found, wrong architecture, etc). This would make it easier to troubleshoot loading game logic.

**Comment by Leonx254** [comment]
Requested feature added in 043ea23
