### ISSUE TITLE
Add numbers above scene filter checkboxes (v5)

### ISSUE THREAD

**Issue by KiaraGale** [RSDKModding/RetroED#128]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this feature has not already been requested.
- [X] I acknowledge the addition of this feature is neither guaranteed nor a priority.
- [X] This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### Requested Feature

The v5 Scene Editor has the Filter checkboxes, but it isn't made clear what they do unless you hover over one of them for several seconds to see the tooltip. This is why I suggest adding numbers above the Filter checkboxes, to make it their functionality and readability easier to understand.
Below is a mock-up of the suggested change:
![filterCheckNumbers](https://github.com/user-attachments/assets/29ce111e-724b-4f3c-a933-2d817c7e3a01)

**Comment by Leonx254** [comment]
Added in 4fb6559
