### ISSUE TITLE
Middle click file tabs to close them

### ISSUE THREAD

**Issue by MegAmi24** [RSDKModding/RetroED#131]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this feature has not already been requested.
- [X] I acknowledge the addition of this feature is neither guaranteed nor a priority.
- [x] This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.

### Editor Tool

Other

### Requested Feature

Pressing the middle click button while the cursor is over a file tab should close it. This feature is in most programs with tabs, so it'd be nice to have here as well.

**Comment by Leonx254** [comment]
Feature added in b89e71f
