### ISSUE TITLE
Screen Resize Bug

### ISSUE THREAD

**Issue by c08oprkiua** [RSDKModding/RetroED#143]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. error when starting program or trying to build).
- [X] I am not reporting an issue with assets/scripts/logic of a specific game/mod; this bug is directly related to the editor itself.
- [X] This bug is not related to any unofficial forks of the editor, and any issues with those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### RSDK Version

v3

### Expected Behavior

The RetroED window should respect the vertical taskbar I have in KDE Plasma

### Actual Behavior

It will set its x stretch to the horizontal size of my screen, leaving an edge of the editor under my taskbar.

### Steps to Reproduce

1. Open RetroED on Linux
2. Mess with anything in the Scene editor
3. Window immediately starts to clip
4. Attempt to fix issue by maximizing the window
5. Window clips but in the other direction
6. Won't let me minimize the size, or if it does, it still sets it back when I do anything

### Screenshots

![image](https://github.com/user-attachments/assets/d3d78742-ce1a-4fb3-9052-ddae5ed5bcaa)
![image](https://github.com/user-attachments/assets/2ca9fd50-e54b-4a5a-99e5-3d468c188d25)

### Was another editor used on the file(s)?

No.

### Platform

Linux

**Comment by c08oprkiua** [comment]
Oh yeah also

I didn't show screenshots of it because I'm not at home to demonstrate it right now, but it also has similar issues with setting a minimum size on my secondary, 4:3 monitor, but it's even worse there (I will get screenshots of it when I get home)

**Comment by Leonx254** [comment]
fixed in [dfaa414](https://github.com/RSDKModding/RetroED/commit/dfaa414128b27477e7ab38a77cadf11264d1f9e2)
