### ISSUE TITLE
Changing an entity's slot ID resets all entity values to 0

### ISSUE THREAD

**Issue by KiaraGale** [RSDKModding/RetroED#145]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. error when starting program or trying to build).
- [X] I am not reporting an issue with assets/scripts/logic of a specific game/mod; this bug is directly related to the editor itself.
- [X] This bug is not related to any unofficial forks of the editor, and any issues with those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### RSDK Version

v5

### Expected Behavior

Changing the entity's ID should change the list placement and nothing else

### Actual Behavior

Changing the entity's ID results in changing the list placement as well as all entity values resetting to defaults/0

### Steps to Reproduce

Change any entity's slot ID to a different value.

### Platform

Windows 11

**Comment by MegAmi24** [comment]
Fixed in cda5059
