### ISSUE TITLE
Duplicate/Incorrectly ordered entity slot IDs

### ISSUE THREAD

**Issue by KiaraGale** [RSDKModding/RetroED#146]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. error when starting program or trying to build).
- [X] I am not reporting an issue with assets/scripts/logic of a specific game/mod; this bug is directly related to the editor itself.
- [X] This bug is not related to any unofficial forks of the editor, and any issues with those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### RSDK Version

v5

### Expected Behavior

Entity slot values should be in numerical order without any duplicate or incorrectly ordered entries

### Actual Behavior

There can be duplicate entity slot IDs in the entity list, as well as incorrectly ordered slot IDs in the entity list

### Steps to Reproduce

Copying and pasting an entity when there's any gaps in the entity list seems to cause this.

### Screenshots

![image](https://github.com/user-attachments/assets/d69a7183-8b76-4fa2-aae8-f3c1f82baeca)
![image](https://github.com/user-attachments/assets/59001a90-8750-4e85-bcfa-c8a9a6462d57)
![image](https://github.com/user-attachments/assets/a4f9fb46-ae69-4bd4-bea2-53282852f09b)

### Platform

Windows 11

### Additional Comments

The scene file this was found in was Mania's Main Menu file, and was previously edited with an older version of RetroED.

**Comment by MegAmi24** [comment]
Fixed in cda5059
