### ISSUE TITLE
Auto-realignment to fill gaps in entity list IDs

### ISSUE THREAD

**Issue by KiaraGale** [RSDKModding/RetroED#147]
### Before opening this issue, I ensure that...

- [X] I have checked **both open and closed** issues and confirmed this feature has not already been requested.
- [X] I acknowledge the addition of this feature is neither guaranteed nor a priority.
- [X] This request is not related to any unofficial forks of the editor, and any requests related to those should be kept in the appropriate repository.

### Editor Tool

Scene Editor

### Requested Feature

Simple (in concept) and low-priority feature, but a tool to mass-shift entities around to fill in entity list number gaps would be incredibly nice, rather than having to manually adjust the slot ID of each entity when deleting an entity in the middle of the list.

**Comment by LittlePlanetCD** [comment]
Solved as of PR #150
